env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2015
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - windows
  quotes:
    - warn
    - double
  semi:
    - error
    - always
  no-console: off
  no-unused-vars: warn
